services:
  - type: web
    name: gym-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
    autoDeploy: true
